LABELS = {'zh': {'title': '吳威震 Wei-Chen Wu｜金融科技・AI・資通安全',
        'description': '國立臺北商業大學財務金融系吳威震副教授。個人履歷、研究計畫、學術著作、教學、產學合作與專業服務。',
        'skip': '跳至主要內容',
        'name': '吳威震',
        'role': '副教授',
        'university': '國立臺北商業大學',
        'department': '財務金融系',
        'nav': [('home', '首頁'),
                ('about', '個人履歷'),
                ('research', '研究'),
                ('publications', '學術著作'),
                ('teaching', '教學'),
                ('industry', '產學合作'),
                ('services', '服務')],
        'menu': '開啟導覽選單',
        'switch': 'Switch to English',
        'hero_top': '國立臺北商業大學 · 財務金融系',
        'hero_text': '區塊鏈、機器學習、量子金融與資通安全',
        'hero_tagline': '智慧金融連結可信未來',
        'explore': '研究計畫',
        'diagram': '三維研究關係圖，呈現區塊鏈、機器學習與量子金融的連結。',
        'diagram_note': '區塊鏈 × 機器學習 × 量子金融',
        'papers_count': '筆著作紀錄',
        'projects_count': '項研究與合作計畫',
        'patents_count': '項發明專利',
        'honors_count': '項榮譽紀錄',
        'research_kicker': '02 / RESEARCH',
        'research_title': '研究領域與計畫',
        'research_intro': '研究方向涵蓋資通安全、人工智慧與金融科技。',
        'areas': [('01', '資通安全', 'CYBERSECURITY', '網路安全、密碼學、加密貨幣與後量子密碼學。'),
                  ('02', '人工智慧', 'ARTIFICIAL INTELLIGENCE', '機器學習與深度學習。'),
                  ('03', '金融科技', 'FINANCIAL TECHNOLOGY', '區塊鏈、去中心化金融與量子金融。')],
        'latest_research': '研究計畫',
        'active': '執行中',
        'records': '筆',
        'pending': '此筆原文已更新，英文翻譯待同步。',
        'source_note': '年份、計畫狀態與引用資訊依履歷紀錄呈現。',
        'publications_kicker': '03 / PUBLICATIONS',
        'publications_title': '學術著作',
        'publications_intro': '期刊論文、研討會論文、專著與專書論文。',
        'publications_note': '論文題名保留原發表語言；同一成果可能收錄於不同類別，數量為原始紀錄筆數。',
        'teaching_kicker': '04 / TEACHING',
        'teaching_title': '教學',
        'teaching_intro': '授課領域、教學實踐研究與海外實習計畫。',
        'teaching_areas': '授課領域',
        'learn_title': '教學與海外實習',
        'learn_text': '教學實踐研究連結金融創新與 AI 應用；學海築夢計畫則將學習延伸至日本的海外專業實習。',
        'industry_kicker': '05 / COLLABORATION',
        'industry_title': '產學合作',
        'industry_intro': '金融教育、加密貨幣與區塊鏈應用相關合作計畫。',
        'patent_label': '智慧財產與技術成果',
        'about_kicker': '01 / CURRICULUM VITAE',
        'about_title': '個人履歷',
        'cv_title': '下載完整履歷',
        'cv_text': '含學經歷、專業服務、全部著作、研究計畫、專利及榮譽。',
        'cv_zh': '中文版 CV',
        'cv_en': 'English CV',
        'honors': '榮譽',
        'footer': '吳威震 · 國立臺北商業大學財務金融系',
        'top': '回到頂端',
        'view_cv': '閱讀履歷',
        'diagram_topics': [('bc', '區塊鏈'), ('ml', '機器學習'), ('qf', '量子金融')],
        'diagram_fields': {
            'bc': ['分散式帳本', '共識演算法', '智慧合約', '零知識證明', '跨鏈通訊'],
            'ml': ['深度學習', '自然語言處理', '電腦視覺', '強化學習', '聯邦學習'],
            'qf': ['量子演算法', '量子機器學習', '量子電路模擬', '量子錯誤更正', '後量子密碼學']},
        'diagram_overview': '研究領域',
        'diagram_subfields': '資訊科技次領域',
        'diagram_back': '返回主領域',
        'diagram_help': '點選圖中節點進入次領域圖。也可使用 Tab 選擇領域並按 Enter 開啟；方向鍵旋轉，加減鍵縮放，Home 重設，Escape 返回主圖。聚焦圖形本身時可按空白鍵暫停或恢復自動旋轉。觸控螢幕可點選領域或左右滑動旋轉。',
        'services_kicker': '06 / PROFESSIONAL SERVICE',
        'services_title': '專業服務',
        'services_intro': '競賽裁判、計畫審查、課程講授、考試委員與專業組織服務。'},
 'en': {'title': 'Wei-Chen Wu | FinTech, AI & Cybersecurity',
        'description': 'Wei-Chen Wu, Associate Professor of Finance at National Taipei University of '
                       'Business. CV, research, publications, teaching, collaboration, and professional '
                       'service.',
        'skip': 'Skip to content',
        'name': 'Wei-Chen Wu',
        'role': 'Associate Professor',
        'university': 'National Taipei University of Business',
        'department': 'Department of Finance',
        'nav': [('home', 'Home'),
                ('about', 'CV'),
                ('research', 'Research'),
                ('publications', 'Publications'),
                ('teaching', 'Teaching'),
                ('industry', 'Collaboration'),
                ('services', 'Service')],
        'menu': 'Open navigation',
        'switch': '切換至中文',
        'hero_top': 'DEPARTMENT OF FINANCE · NTUB',
        'hero_text': 'Blockchain, machine learning, quantum finance, and cybersecurity',
        'hero_tagline': 'Connecting smart finance to a trusted future.',
        'explore': 'Research projects',
        'diagram': 'Three-dimensional research connections between blockchain, machine learning, and quantum '
                   'finance.',
        'diagram_note': 'Blockchain × Machine learning × Quantum finance',
        'papers_count': 'publication records',
        'projects_count': 'research & partnership projects',
        'patents_count': 'invention patent',
        'honors_count': 'honors',
        'research_kicker': '02 / RESEARCH',
        'research_title': 'Research areas & projects',
        'research_intro': 'Research in cybersecurity, artificial intelligence, and financial technology.',
        'areas': [('01',
                   'Cybersecurity',
                   'SECURITY & PRIVACY',
                   'Network security, cryptography, cryptocurrency, and post-quantum cryptography.'),
                  ('02',
                   'Artificial intelligence',
                   'MACHINE & DEEP LEARNING',
                   'Machine learning and deep learning.'),
                  ('03',
                   'Financial technology',
                   'BLOCKCHAIN & QUANTUM FINANCE',
                   'Blockchain, decentralized finance, and quantum finance.')],
        'latest_research': 'Research projects',
        'active': 'In progress',
        'records': 'records',
        'pending': 'Source updated. English translation pending; current original shown.',
        'source_note': 'Dates, project status and citations follow the CV records.',
        'publications_kicker': '03 / PUBLICATIONS',
        'publications_title': 'Publications',
        'publications_intro': 'Journal articles, conference papers, books, and book chapters.',
        'publications_note': 'Titles retain their publication language where appropriate. Counts represent '
                             'source records; some work appears in more than one category.',
        'teaching_kicker': '04 / TEACHING',
        'teaching_title': 'Teaching',
        'teaching_intro': 'Teaching areas, teaching practice research, and overseas internships.',
        'teaching_areas': 'Teaching Areas',
        'learn_title': 'Teaching & overseas internships',
        'learn_text': 'Teaching practice research connects financial innovation with AI applications. '
                      'Overseas internship projects extend learning to professional settings in Japan.',
        'industry_kicker': '05 / COLLABORATION',
        'industry_title': 'Industry collaboration',
        'industry_intro': 'Collaborative projects in financial education, cryptocurrency, and blockchain '
                          'applications.',
        'patent_label': 'Intellectual property & technology',
        'about_kicker': '01 / CURRICULUM VITAE',
        'about_title': 'Curriculum vitae',
        'cv_title': 'Download the complete CV',
        'cv_text': 'Education, experience, professional service, all publications, projects, patents, and '
                   'honors.',
        'cv_zh': '中文版 CV',
        'cv_en': 'English CV',
        'honors': 'Honors',
        'footer': 'Wei-Chen Wu · Department of Finance, NTUB',
        'top': 'Back to top',
        'view_cv': 'Read CV',
        'diagram_topics': [('bc', 'Blockchain'), ('ml', 'Machine learning'), ('qf', 'Quantum finance')],
        'diagram_fields': {
            'bc': ['Distributed ledgers', 'Consensus algorithms', 'Smart contracts', 'Zero-knowledge proofs', 'Cross-chain communication'],
            'ml': ['Deep learning', 'Natural language processing', 'Computer vision', 'Reinforcement learning', 'Federated learning'],
            'qf': ['Quantum algorithms', 'Quantum machine learning', 'Quantum circuit simulation', 'Quantum error correction', 'Post-quantum cryptography']},
        'diagram_overview': 'Research areas',
        'diagram_subfields': 'Information technology subfields',
        'diagram_back': 'Back to research areas',
        'diagram_help': 'Select a graph node to open its subfields. Use Tab and Enter '
                        'to select an area, arrow keys to rotate, plus or minus to zoom, Home to reset, '
                        'and Escape to return to the main graph. When the graph itself is focused, press Space '
                        'to pause or resume automatic rotation. On touchscreens, tap an area or swipe '
                        'horizontally to rotate.',
        'services_kicker': '06 / PROFESSIONAL SERVICE',
        'services_title': 'Professional service',
        'services_intro': 'Competition judging, project review, course instruction, examinations, and '
                          'professional organizations.'}}
