LABELS = {
    'zh': {
        'title': '吳威震 Wei-Chen Wu｜金融科技・AI・資通安全',
        'description': '國立臺北商業大學財務金融學系吳威震副教授。探索區塊鏈、人工智慧、資通安全與量子金融的研究、教學與產學合作。',
        'skip': '跳至主要內容', 'name': '吳威震', 'role': '副教授',
        'university': '國立臺北商業大學', 'department': '財務金融學系',
        'nav': [('home', '首頁'), ('research', '研究'), ('publications', '學術著作'), ('teaching', '教學'), ('industry', '產學合作'), ('about', '關於我')],
        'contact': '加入研究團隊', 'menu': '開啟導覽選單', 'switch': 'Switch to English',
        'hero_top': '探索金融與科技的交會點', 'hero_1': '讓金融更智慧，', 'hero_2': '讓信任更堅實。',
        'hero_text': '從區塊鏈到量子金融，從人工智慧到資訊安全。一起把好奇心，變成能解決真實問題的研究。',
        'explore': '探索研究方向', 'talk': '聊聊你的研究想法', 'diagram': '研究領域關係圖：人工智慧、資通安全與金融科技交會於可信任的金融創新。',
        'diagram_core': '可信任的', 'diagram_core_2': '金融創新', 'diagram_ai': '人工智慧', 'diagram_security': '資通安全', 'diagram_finance': '金融科技',
        'diagram_note': '區塊鏈 × 機器學習 × 量子金融',
        'papers_count': '筆著作紀錄', 'projects_count': '項研究與合作計畫', 'patents_count': '項發明專利', 'honors_count': '項榮譽紀錄',
        'research_kicker': '01 / RESEARCH', 'research_title': '在跨領域之間，找到下一個問題。',
        'research_intro': '以安全為基礎，結合人工智慧與金融應用，探索值得信任的數位未來。',
        'areas': [('01', '資通安全', 'CYBERSECURITY', '網路安全、密碼學與加密貨幣，從身分認證到隱私保護。'), ('02', '人工智慧', 'ARTIFICIAL INTELLIGENCE', '機器學習與深度學習，探索資料中的規律與可用洞見。'), ('03', '金融科技', 'FINANCIAL TECHNOLOGY', '區塊鏈、去中心化金融與量子金融，連結理論與實際應用。')],
        'source_areas': '研究領域', 'active_research': '研究計畫', 'latest_research': '從正在進行的研究出發',
        'active': '執行中', 'full_list': '展開完整清單', 'records': '筆', 'pending': '此筆原文已更新，英文翻譯待同步。',
        'source_note': '年份、計畫狀態與引用資訊依履歷紀錄呈現。',
        'publications_kicker': '02 / PUBLICATIONS', 'publications_title': '讓想法經得起驗證。',
        'publications_intro': '期刊、國際研討會與專書，記錄研究一路累積的成果。',
        'publications_note': '論文題名保留原發表語言；同一成果可能收錄於不同類別，數量為原始紀錄筆數。',
        'teaching_kicker': '03 / TEACHING', 'teaching_title': '從寫下第一行程式，到提出自己的解法。',
        'teaching_intro': '金融科技、程式語言與人工智慧：結合專題實作、數位教學助理與跨領域學習。',
        'teaching_areas': '授課領域', 'learn_title': '把學習帶進真實世界',
        'learn_text': '教學實踐研究連結金融創新與 AI 應用；學海築夢計畫則將學習延伸至日本的海外專業實習。',
        'teaching_projects': '教學與海外實習計畫',
        'industry_kicker': '04 / COLLABORATION', 'industry_title': '讓研究走進產業現場。',
        'industry_intro': '從金融教育、加密貨幣公益應用，到區塊鏈照護服務，與產業共同探索技術落地的可能。',
        'industry_cta': '洽談產學合作', 'patent_label': '智慧財產與技術成果',
        'about_kicker': '05 / ABOUT', 'about_title': '吳威震', 'profile_expand': '學經歷、學術服務與專業證照',
        'cv_title': '完整學術履歷', 'cv_text': '含學經歷、全部著作、研究計畫、專利及榮譽。',
        'cv_zh': '中文版 CV', 'cv_en': 'English CV', 'honors': '榮譽與肯定',
        'join_kicker': 'YOUR NEXT CHAPTER', 'join_title': '你的好奇心，\n可以是研究的起點。',
        'join_text': '對金融科技、AI、區塊鏈或資安有興趣？歡迎分享你的背景、想探索的問題，以及期待投入的方向，一起討論研究與合作的可能。',
        'email': '寄信聯絡', 'message': '傳送訊息', 'phone': '聯絡電話',
        'footer': '吳威震 · 國立臺北商業大學財務金融學系', 'top': '回到頂端',
        'chat_title': '和吳老師聊聊', 'chat_subtitle': '研究方向・加入團隊・產學合作',
        'chat_close': '關閉對話', 'chat_greeting': '歡迎！可以先介紹自己，或告訴我你感興趣的研究方向。老師回覆後，會顯示在這個對話中。',
        'chat_privacy': '送出後，訊息會轉交老師的 LINE。對話保存 {days} 天；請使用同一瀏覽器查看回覆，並避免傳送敏感資料。',
        'chat_unavailable': '線上留言尚未開放，歡迎先以 Email 聯繫老師。',
        'chat_name': '你的稱呼', 'chat_name_placeholder': '希望老師如何稱呼你？', 'chat_body': '訊息',
        'chat_placeholder': '介紹自己，或分享你的研究想法…', 'chat_send': '傳送訊息', 'chat_sending': '傳送中…',
        'chat_accepted': '已提交至 LINE，等待老師回覆。', 'chat_failure': '暫時無法送達 LINE。內容已保留，請稍後重試或改寄 Email。',
        'chat_rate': '訊息較多，請稍後再試，或改寄 Email。', 'chat_session': '連線已更新，請重新開啟對話後再試。',
        'chat_retry': '重試傳送', 'chat_pending': '等待提交', 'chat_failed': '傳送未完成', 'chat_teacher': '吳老師',
        'chat_fetch_error': '暫時無法取得回覆，正在重新連線。', 'chat_no_js': '請啟用 JavaScript 使用聊天功能，或直接寄信聯絡。',
    },
    'en': {
        'title': 'Wei-Chen Wu | FinTech, AI & Cybersecurity',
        'description': 'Wei-Chen Wu, Associate Professor of Finance at National Taipei University of Business. Research in blockchain, artificial intelligence, cybersecurity and quantum finance.',
        'skip': 'Skip to content', 'name': 'Wei-Chen Wu', 'role': 'Associate Professor',
        'university': 'National Taipei University of Business', 'department': 'Department of Finance',
        'nav': [('home', 'Home'), ('research', 'Research'), ('publications', 'Publications'), ('teaching', 'Teaching'), ('industry', 'Collaboration'), ('about', 'About')],
        'contact': 'Join the research', 'menu': 'Open navigation', 'switch': '切換至中文',
        'hero_top': 'AT THE INTERSECTION OF FINANCE & TECHNOLOGY', 'hero_1': 'Smarter finance.', 'hero_2': 'Stronger trust.',
        'hero_text': 'From blockchain to quantum finance. From artificial intelligence to cybersecurity. Turn your curiosity into research that addresses real problems.',
        'explore': 'Explore the research', 'talk': 'Share your research ideas',
        'diagram': 'Research diagram: artificial intelligence, cybersecurity and financial technology intersect in trusted financial innovation.',
        'diagram_core': 'TRUSTED', 'diagram_core_2': 'FINANCIAL INNOVATION', 'diagram_ai': 'Artificial intelligence', 'diagram_security': 'Cybersecurity', 'diagram_finance': 'Financial technology',
        'diagram_note': 'BLOCKCHAIN × MACHINE LEARNING × QUANTUM FINANCE',
        'papers_count': 'publication records', 'projects_count': 'research & partnership projects', 'patents_count': 'invention patent', 'honors_count': 'honors',
        'research_kicker': '01 / RESEARCH', 'research_title': 'The next question lives between disciplines.',
        'research_intro': 'A foundation in security. New possibilities through AI and finance. Research toward a digital future we can trust.',
        'areas': [('01', 'Cybersecurity', 'SECURITY & PRIVACY', 'Network security, cryptography and cryptocurrency, from authentication to privacy protection.'), ('02', 'Artificial intelligence', 'MACHINE & DEEP LEARNING', 'Machine learning and deep learning to discover patterns and useful insights in data.'), ('03', 'Financial technology', 'BLOCKCHAIN & QUANTUM FINANCE', 'Blockchain, decentralized finance and quantum finance, connecting theory with applications.')],
        'source_areas': 'Research Areas', 'active_research': 'Research projects', 'latest_research': 'Start with a current research question',
        'active': 'In progress', 'full_list': 'Explore all records', 'records': 'records', 'pending': 'Source updated. English translation pending; current original shown.',
        'source_note': 'Dates, project status and citations follow the CV records.',
        'publications_kicker': '02 / PUBLICATIONS', 'publications_title': 'Ideas, put to the test.',
        'publications_intro': 'Journal articles, conference papers and books document an evolving body of research.',
        'publications_note': 'Titles retain their publication language where appropriate. Counts represent source records; some work appears in more than one category.',
        'teaching_kicker': '03 / TEACHING', 'teaching_title': 'From your first line of code to your own solution.',
        'teaching_intro': 'FinTech, programming languages and AI, brought together through projects, digital teaching assistants and interdisciplinary learning.',
        'teaching_areas': 'Teaching Areas', 'learn_title': 'Take learning into the real world',
        'learn_text': 'Teaching practice research connects financial innovation with AI applications. Overseas internship projects extend learning to professional settings in Japan.',
        'teaching_projects': 'Teaching & overseas internship projects',
        'industry_kicker': '04 / COLLABORATION', 'industry_title': 'Research that reaches the real world.',
        'industry_intro': 'Exploring practical applications with industry, from financial education and cryptocurrency for social good to blockchain-based care services.',
        'industry_cta': 'Discuss a collaboration', 'patent_label': 'Intellectual property & technology',
        'about_kicker': '05 / ABOUT', 'about_title': 'Wei-Chen Wu', 'profile_expand': 'Education, experience, academic service & certifications',
        'cv_title': 'The complete academic CV', 'cv_text': 'Education, experience, all publications, projects, patents and honors.',
        'cv_zh': '中文版 CV', 'cv_en': 'English CV', 'honors': 'Honors & recognition',
        'join_kicker': 'YOUR NEXT CHAPTER', 'join_title': 'Your curiosity.\nA new research question.',
        'join_text': 'Interested in FinTech, AI, blockchain or cybersecurity? Share your background, a question you want to explore and the direction you would like to pursue. Let’s discuss research and collaboration.',
        'email': 'Get in touch by email', 'message': 'Send a message', 'phone': 'Phone',
        'footer': 'Wei-Chen Wu · Department of Finance, NTUB', 'top': 'Back to top',
        'chat_title': 'Talk with Prof. Wu', 'chat_subtitle': 'Research · Joining the team · Collaboration',
        'chat_close': 'Close conversation', 'chat_greeting': 'Welcome! Introduce yourself or share a research direction that interests you. The professor’s reply will appear in this conversation.',
        'chat_privacy': 'Your message is forwarded to the professor’s LINE account and kept for {days} days. Use this same browser to check replies. Please avoid sharing sensitive information.',
        'chat_unavailable': 'Website messaging is not open yet. Please contact the professor by email.',
        'chat_name': 'Your name', 'chat_name_placeholder': 'How should we address you?', 'chat_body': 'Message',
        'chat_placeholder': 'Introduce yourself or share a research idea…', 'chat_send': 'Send message', 'chat_sending': 'Sending…',
        'chat_accepted': 'Submitted to LINE. Waiting for the professor’s reply.', 'chat_failure': 'LINE is temporarily unavailable. Your message is saved. Please retry or use email.',
        'chat_rate': 'Too many messages. Please try again later or use email.', 'chat_session': 'Your connection has changed. Please reopen the conversation and try again.',
        'chat_retry': 'Retry sending', 'chat_pending': 'Awaiting submission', 'chat_failed': 'Not yet submitted', 'chat_teacher': 'Prof. Wu',
        'chat_fetch_error': 'Replies are temporarily unavailable. Reconnecting…', 'chat_no_js': 'Enable JavaScript to chat, or contact the professor by email.',
    },
}
